sudo: required
language: generic
services: docker
env:
- HHVM_VERSION=latest
- HHVM_VERSION=nightly
install:
- docker pull hhvm/hhvm:$HHVM_VERSION
script:
- docker run --rm -w /var/source -v $(pwd):/var/source hhvm/hhvm:$HHVM_VERSION ./.travis.sh
notifications:
  slack:
    rooms:
    - secure: bQY7/pt4nF2415Sy6defCvketOaqfrB/FnnotOvwH63vy73KDn1jvwD2JoAK2STUPa/hbta/1mNqYMBn7NcxwvhXGO41wvrPfJAQZ+WI7eVENAPv/Ok/QEAX24e6ssER5XG8EMK2Db5dxoTt4CsMfua/AfK6TkoGOJsaiirZlycBVCEXR0PfBjNP9FoG+veo+uZHAD4CMorriNnfCjaiKJLVG4HKlDiJJ45XsGxz6LDIHAyeMCDb3SThnYGBOUzefKgTlln+WdEMFcNzHzbzTpMnp57gJtEy1a4+YaSOKBDvswUlFLkZNFP1ORjrDAIQ+eaWta1pu7YZdHX2lpBkOVboYTQpJTeFXd7ZUQfBuZFZJZGFc7UXJrnDnwVGpbisYBm6uAlyQvatztEgeSNqB2z6sVpwPL8zPk3QgEPEeo2O2A9yOMspqe+6rXAfFiKNbA7QVvdjAxKFrCHdIPuhMcrDOdUavPWPGrnu3/12kP1UwcfKN8C9KUEYIZEiMYDr7ch3p8PHEWToyVY1xSh/DeVzXBnvOLOgQAHbhnAv1qeH/aia4tgzEmNg49C4+8k6klLzTRj2mVNtSSlZtvfUe7Z3frPkbQhUg9KZEdhtORPA1fCVMx1fAcS2j1IBKjYq/Vzu7OrHslqSkyZNg+Y809daohGHJWFAGW/lRf8kOGs=
    - secure: D65AhBG2DQ7pm78C+UV71zv0SLIZahdJE9+/tA2CEJ+0jiq4ekorZkeaqMNv39FPY6EXhrn7MffY69xEDzwpVffTdtQfW67l+A5SjW8rRK0d3rGrSl7HXV5TeYZax3DM4Vd5AgwEyfmBQX5acAK6Qqo5w5/k6AhCHOJl/LUEWM070tPdosbQqmQnRldn5TwK7zs0rIP3b9MxDJxPm3GJbjMdbdDFyy/68rNCHYNYDqK7GgWIxJPHpELSjeRCndIIRrewoVrjJ1KoC127RrqCALDI6ZyuKUzKccXyG2ldQBJh96PAn2XtbYcHlxR5K/sAct4R334n0Bswnc28gNWDJjZtnALvSXfG9UEhoUaX3CxYQwHddcppESayaOj8r0r2H8GTlrPJW9P4+IryHpiEED4G5kTtd5xVgnv8+5fvhIGT8Dp+D2KewSsJO8pf02URZpJ2id1pNq/tx/IhPS3N6zABv7q91ijqUiCXhRnf1xLH48DMjbSNo/MZJoOEJXh2zqrmnumlx/DK05jORbbVLNMVPkvXgwfw40tYcGIjCUtRn5U22hCmDEQCbLQ7Hf4kVFykJoUiEJNAdasAzkplKYJ0Tj7RHQ0P8xB9rs1dIFSQBw/sNAI8qqMaFgRkf2u77HeVOnoYxB0tGWvaf03rNzBuJODmM2nYRekHQZDlgS4=
