sudo: required
language: generic
services: docker
env:
  matrix:
  - HHVM_VERSION=nightly
  global:
    secure: RQoEvVCsF3EmU3iE3Y3M/dCcTi06yZ1qOyGTewedfBr/kI8bxNRB/U9Nw2yJoOhe8MVfdk61i5HDh7d5+ipFJHwwFwFagh/x6hNPqp3Es9nM9tUJOCKdbOxT4bhCH6SdotFSU141KQE+fcccAijUrsFB8rP6UyTBGqJwp/8IWvfJjAcFzs0Zrba5J3a3YOl202ag3ECdPDzjqrRFBp1lZ82tDEQzEJemhDOo2mBPRQpUv6Q473Tp4lc+XbM6Bib/fQN6r9HZFU2bawu4ph7X6fOvyAkcSjQqdDKFXdIkzCTxIt4Yluih5D3Oub6n9NQQI4VHTubbgI9xm8pR7pKETd5XYWVcnrYM/LfkIUj9w/6QTv8krLK7E6xyeL/kpnY0joFS5Grn8cZI3g8hm6kjS+qO9gmG42yfF8nOpL+JtFNVzyrXuvkUBCf36NYTW3dPv/gH6idIg3qBbGAMVS5ZFpqbw/+pHKAESJg1yuSy1w2D82mmZHnALYuKKU5wsTKT++oqRu2xSP6Bdla9of85tokFiMb5R1gVP46jNqAEGqj3ZDSBfwe03PZubsf3yjl7urbeEvW2svDdp4E8n/Cg1yGub6vhCzaz0v48RrL7Is90R8CCIIY4xQDNjniW0G5buDr0KT1rsy1RzJPCxXiCWkImpkhDgBBIbvfe4SOc4pE=
install:
- docker pull hhvm/hhvm:$HHVM_VERSION
script:
- docker run --rm -w /var/source -v $(pwd):/var/source hhvm/hhvm:$HHVM_VERSION ./.travis.sh
notifications:
  slack:
    secure: rmhFMa9mn+O+jvPwEBFfGajP6XnbaWqE6LpuIbTjMuCIbhst5qAAXKNL29z4cG52c6oB20te84bUullj7fZVOLayJJhHzor8Cmx8bUoFyxj54kuLe+BvvDbpFv7ZEOxmKBFirzgFiUcK46J/FY/8njU1B1UKQ9VCEx5kozLXZr4pF4hwKY494zk7fl1bJU1S6Qu1T1WYQEubCigmPAroeyERtzl2Vyxpt4WUerg4g6YfXH4YW/XDhiWFsIxZe50nF8C0VYxxc2ZSv0pTA2X1GjzdG3nivHP9aSm8WOqqvPUL5BwEP4TQUWAMUARxqogpR5AVvBhr2FjU0k6RdJgKtCQMjA7UV+K9NXRgnposq1yHJ0ReXVZgQEOrsVJNyQhEo5bgzIxEHsy/8KqQct+jt6uaGRED/JGw2MArpX6kbX6rV+J3In6Wp4wCGYnRbnRsg+uo2kPYm+Ph66OaZOGbKGfZp476D4rJyks5E4IankYlA0c9ZsyHUypSAcUC5JRg/p6rb3rJkbP+TlFvETwJTuiH5OTVZRnyz8uNrNEFJbN3Qdv6UpO75jmR27rjTou+jfX4vkpWReQ88NFGeF0ENjvhKd9lA6hm5CaXxOd0tHfIUwVpzBZ3ygaITCoCLyABuu74hlTcHiCprlI4pm6l4acVc8gGIbQX9qrqGuEnycw=
