name: Continuous Integration
on:
  push:
  pull_request:
  schedule:
    - cron: "42 15 * * *"
jobs:
  build:
    name: HHVM ${{matrix.hhvm}} - ${{matrix.os}}
    strategy:
      # Run tests on all OS's and HHVM versions, even if one fails
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        hhvm:
          - "4.158"
          - latest
          - nightly
    runs-on: ${{matrix.os}}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hhvm/actions/hack-lint-test@master
        with:
          hhvm: ${{matrix.hhvm}}
          # We need bin/hhast-lint instead of vendor/bin/hhast-lint
          skip_lint: true
      - name: Lint
        run: bin/hhast-lint
      - name: Check for manually modified codegen
        run: vendor/bin/hh-codegen-verify-signatures codegen/
  update-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hhvm/actions/hack-lint-test@master
        with:
          hhvm: nightly
          skip_lint: true
          skip_tests: true
      - if: github.event_name	== 'pull_request'
        run: bin/update-codegen
      - if: github.event_name	== 'pull_request'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: Update schema
      - if: github.event_name	!= 'pull_request'
        uses: actions/checkout@v3
        with:
          submodules: true
          repository: facebook/hhvm
          path: ./.var/tmp/hhvm
      - if: github.event_name	!= 'pull_request'
        run: bin/update-schema --hhvm-path=./.var/tmp/hhvm
      - if: github.event_name	!= 'pull_request'
        uses: peter-evans/create-pull-request@v4
        with:
          branch: update-schema/${{github.ref_name}}
          title: Update schema
          commit-message: Update schema
      - if: github.event_name	!= 'pull_request'
        run: git checkout -B "${{github.ref_name}}"
      - if: github.event_name	!= 'pull_request'
        run: bin/update-codegen --dont-update-ast --update-latest-breaking-version
      - if: github.event_name	!= 'pull_request'
        name: Extract LATEST_BREAKING_HHVM_VERSION from latest_breaking_version.hack
        run: |
          [[ \
            "$(<codegen-no-rebuild/latest_breaking_version.hack)" \
            =~ const\ string\ LATEST_BREAKING_HHVM_VERSION\ =\ \'([0-9]+\.[0-9]+)\. \
          ]] && \
          echo "LATEST_BREAKING_HHVM_VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
      - if: github.event_name	!= 'pull_request'
        uses: mikefarah/yq@v4
        with:
          cmd:
            yq \
              '.jobs.build.strategy.matrix.hhvm = ["'"$LATEST_BREAKING_HHVM_VERSION"'", "latest", "nightly"]' \
              .github/workflows/build-and-test.yml
      - if: github.event_name	!= 'pull_request'
        uses: peter-evans/create-pull-request@v4
        with:
          branch: update-latest-breaking-version/${{github.ref_name}}
          title: Update schema to a backward incompatible version
          commit-message: Update the latest breaking version
          body: |
            This PR updates assumes the latest schema is a breaking change.
            Feel free to close this PR if the schema is actually backward compatible with previous schema versions.
