name: Continuous Integration
on:
  push:
  pull_request:
  schedule:
    - cron: "42 15 * * *"
jobs:
  build:
    name: HHVM ${{matrix.hhvm}} - ${{matrix.os}}
    strategy:
      # Run tests on all OS's and HHVM versions, even if one fails
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        hhvm:
          - "4.158"
          - latest
          - nightly
    runs-on: ${{matrix.os}}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hhvm/actions/hack-lint-test@master
        with:
          hhvm: ${{matrix.hhvm}}
          # We need bin/hhast-lint instead of vendor/bin/hhast-lint
          skip_lint: true
      - name: Lint
        run: bin/hhast-lint
      - name: Check for manually modified codegen
        run: vendor/bin/hh-codegen-verify-signatures codegen/
  update-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hhvm/actions/hack-lint-test@master
        with:
          hhvm: nightly
          skip_lint: true
          skip_tests: true
      - uses: actions/checkout@v3
        with:
          submodules: true
          repository: facebook/hhvm
          path: ./.var/tmp/hhvm
      - run: bin/update-schema --hhvm-path=./.var/tmp/hhvm
      - uses: peter-evans/create-pull-request@v4
        with:
          branch: update-schema/${{github.ref}}
