name: Continuous Integration
on:
  push:
  pull_request:
  schedule:
    - cron: '42 15 * * *'
jobs:
  build:
    name: HHVM macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew developer on
      - run: brew tap hhvm/hhvm
      - run: brew update
      - run: brew install krb5 fribidi
      - run: brew install hhvm-4.128
      - run: brew linkage hhvm-4.128
      - run: lldb --batch -o run -o quit -- /usr/local/bin/hhvm --version
