name: Continuous Integration
on:
  push:
  pull_request:
  schedule:
    - cron: '42 15 * * *'
jobs:
  build:
    name: HHVM macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          brew tap hhvm/hhvm
          brew update
          brew install hhvm-4.128
          lldb --batch -o run -o quit -- hhvm --version
