name: Update Schema
on:
  push:
  pull_request:
  schedule:
    - cron: "42 15 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          submodules: true
          repository: facebook/hhvm
          path: ./.var/tmp/hhvm
      - uses: hhvm/actions/install-hack@master
        with:
          hhvm: nightly
      - run: bin/update-schema --hhvm-path=./.var/tmp/hhvm
      - uses: peter-evans/create-pull-request@v4
        with:
          branch: update-schema/${{github.ref}}
